import './global.css';
import Providers from './providers';
import { Poppins } from 'next/font/google'; 

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Welcome to seller-ui',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`min-h-screen ${poppins.variable} font-sans`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
